"""Internal metadata attached to durable conversation messages."""

from __future__ import annotations

from time import time as wall_time
from typing import Any, MutableMapping, Optional, TypeVar


# These fields describe Hermes' durable record and timeline display, not
# provider-visible message content. The request builder strips them from every
# outgoing copy and the token estimator ignores them: one set, so an estimate
# never prices bytes the provider never receives (an edit's inline_diff in
# display_metadata is ~9KB and would trigger premature compaction).
_TODO_SNAPSHOT_PROVENANCE_KEY = "_todo_snapshot_provenance"
_TODO_SNAPSHOT_LIVE_PROVENANCE = object()
_TODO_SNAPSHOT_PERSISTED_PROVENANCE = object()

PERSISTENCE_ONLY_MESSAGE_FIELDS = frozenset({
    "timestamp", "display_kind", "display_metadata", "_row_id", _TODO_SNAPSHOT_PROVENANCE_KEY,
})

_Message = TypeVar("_Message", bound=MutableMapping[str, Any])


def stamp_live_todo_snapshot(message: _Message) -> _Message:
    """Mark a Todo carrier created by Hermes' compression boundary."""
    message[_TODO_SNAPSHOT_PROVENANCE_KEY] = _TODO_SNAPSHOT_LIVE_PROVENANCE
    return message


def stamp_persisted_todo_snapshot(message: _Message) -> _Message:
    """Mark a Todo carrier materialized from SessionDB with process-local provenance."""
    message[_TODO_SNAPSHOT_PROVENANCE_KEY] = _TODO_SNAPSHOT_PERSISTED_PROVENANCE
    return message


def clear_todo_snapshot_provenance(message: _Message) -> _Message:
    message.pop(_TODO_SNAPSHOT_PROVENANCE_KEY, None)
    return message


def has_persisted_todo_snapshot_provenance(message: Any) -> bool:
    """Whether a message crossed SessionDB's trusted decode boundary as a Todo carrier."""
    return (
        isinstance(message, MutableMapping)
        and message.get(_TODO_SNAPSHOT_PROVENANCE_KEY) is _TODO_SNAPSHOT_PERSISTED_PROVENANCE
    )


def has_trusted_todo_snapshot_provenance(message: Any) -> bool:
    """Whether the carrier was generated by compression or decoded from its durable row."""
    if not isinstance(message, MutableMapping):
        return False
    marker = message.get(_TODO_SNAPSHOT_PROVENANCE_KEY)
    return marker is _TODO_SNAPSHOT_LIVE_PROVENANCE or marker is _TODO_SNAPSHOT_PERSISTED_PROVENANCE


def stamp_message_timestamp(
    message: _Message,
    *,
    timestamp: Optional[float] = None,
) -> _Message:
    """Attach a creation timestamp without replacing source-provided time.

    Gateway adapters can supply the platform event time; all other callers use
    the local wall clock. Returns the same mapping for use at append sites.
    """
    if message.get("timestamp") is None:
        message["timestamp"] = wall_time() if timestamp is None else timestamp
    return message


def append_message(
    messages: list[Any],
    message: _Message,
    *,
    timestamp: Optional[float] = None,
) -> _Message:
    """Stamp and append one live transcript message."""
    messages.append(stamp_message_timestamp(message, timestamp=timestamp))
    return message
